# Generated by Django 4.2.29 on 2026-03-25 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Campus', 'Campus'), ('Faculty', 'Faculty'), ('Department', 'Department')], max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('scheduling_config', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstraintBlueprint',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('param_schema', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('year_level', models.SmallIntegerField(blank=True, null=True)),
                ('weekly_hours_lecture', models.SmallIntegerField(blank=True, null=True)),
                ('weekly_hours_lab', models.SmallIntegerField(default=0)),
                ('requirement', models.CharField(blank=True, choices=[('COMPULSORY', 'COMPULSORY'), ('ELECTIVE', 'ELECTIVE'), ('TECHNICAL_ELECTIVE', 'TECHNICAL_ELECTIVE'), ('AREA_ELECTIVE', 'AREA_ELECTIVE'), ('UNIVERSITY_ELECTIVE', 'UNIVERSITY_ELECTIVE')], max_length=50, null=True)),
                ('default_credits', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.academicunit')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_enrollment', models.IntegerField(blank=True, null=True)),
                ('section_code', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.coursecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'MIDTERM'), ('FINAL', 'FINAL'), ('MAKEUP', 'MAKEUP'), ('QUIZ', 'QUIZ'), ('OTHER', 'OTHER')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('is_common', models.BooleanField(default=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ExamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.exam')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedSolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_id', models.UUIDField()),
                ('solution_type', models.CharField(choices=[('CourseSchedule', 'CourseSchedule'), ('ExamSchedule', 'ExamSchedule')], default='CourseSchedule', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('solver_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_plan', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], default='Free', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeGridTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_grid_templates', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.academicunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_mask', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('kind', models.CharField(choices=[('LECTURE', 'LECTURE'), ('LAB', 'LAB'), ('EXAM', 'EXAM')], default='LECTURE', max_length=20)),
                ('is_excluded', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='core.timegridtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_range', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Active', 'Active'), ('Archived', 'Archived')], default='Planning', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size_estimate', models.IntegerField(blank=True, null=True)),
                ('year_level', models.IntegerField(blank=True, null=True)),
                ('academic_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_groups', to='core.academicunit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_level', models.SmallIntegerField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.organization')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SectionMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.IntegerField()),
                ('modality', models.CharField(choices=[('In-Person', 'In-Person'), ('Online-Sync', 'Online-Sync'), ('Online-Async', 'Online-Async'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('pattern', models.CharField(choices=[('EVERY_WEEK', 'EVERY_WEEK'), ('ODD_WEEKS', 'ODD_WEEKS'), ('EVEN_WEEKS', 'EVEN_WEEKS')], default='EVERY_WEEK', max_length=20)),
                ('required_resources', models.JSONField(blank=True, default=dict)),
                ('is_fixed', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_id', models.UUIDField(blank=True, null=True)),
                ('target_scope', models.JSONField(blank=True, default=dict)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('weight', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('blueprint_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.constraintblueprint')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_constraints', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=255, null=True)),
                ('availability_exceptions', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('academic_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='core.academicunit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'MIDTERM'), ('FINAL', 'FINAL'), ('MAKEUP', 'MAKEUP'), ('QUIZ', 'QUIZ'), ('OTHER', 'OTHER')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_periods', to='core.term')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInvigilator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(default='Invigilator', max_length=50)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilators', to='core.examassignment')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilators', to='core.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='ExamDateSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_slots', to='core.examperiod')),
            ],
        ),
        migrations.AddField(
            model_name='examassignment',
            name='exam_date_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.examdateslot'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_assignments', to='core.resource'),
        ),
        migrations.AddField(
            model_name='examassignment',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='core.generatedsolution'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='core.examperiod'),
        ),
        migrations.AddField(
            model_name='exam',
            name='sections',
            field=models.ManyToManyField(related_name='exams', to='core.coursesection'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.term')),
            ],
        ),
        migrations.AddField(
            model_name='coursesection',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='core.instructor'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sections', to='core.coursesection'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='student_groups',
            field=models.ManyToManyField(blank=True, related_name='sections', to='core.studentgroup'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sections', to='core.term'),
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PREREQUISITE', 'PREREQUISITE'), ('COREQUISITE', 'COREQUISITE')], default='PREREQUISITE', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites_for', to='core.coursecatalog')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prerequisite_of', to='core.coursecatalog')),
            ],
        ),
        migrations.AddField(
            model_name='coursecatalog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.organization'),
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_entity', models.CharField(choices=[('Room', 'Room'), ('Course', 'Course'), ('Instructor', 'Instructor')], max_length=50)),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(choices=[('Boolean', 'Boolean'), ('Number', 'Number'), ('Select', 'Select')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.sectionmeeting')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.resource')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.generatedsolution')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='core.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='academicunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_units', to='core.organization'),
        ),
        migrations.AddField(
            model_name='academicunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.academicunit'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='uq_org_email'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['attributes'], name='ix_resource_attributes'),
        ),
        migrations.AddIndex(
            model_name='instructor',
            index=models.Index(fields=['availability_exceptions'], name='ix_instructor_exceptions'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['section'], name='ix_enrollment_section'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='ix_enrollment_student'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'section'), name='uq_student_section'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.UniqueConstraint(fields=('course', 'prerequisite'), name='uq_course_prereq'),
        ),
        migrations.AddConstraint(
            model_name='courseprerequisite',
            constraint=models.CheckConstraint(check=models.Q(('course', models.F('prerequisite')), _negated=True), name='chk_no_self_prereq'),
        ),
    ]
