# Generated by Django 6.0.5 on 2026-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resource_exam_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecatalog',
            name='exam_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='excluded_from_optimization',
            field=models.BooleanField(default=False),
        ),
    ]
