# Generated by Django 6.0.5 on 2026-05-12 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_exam_duration_and_excluded_from_optimization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='excluded_from_optimization',
        ),
        migrations.CreateModel(
            name='ExamPeriodSectionExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_exclusions', to='core.coursesection')),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='core.examperiod')),
            ],
            options={
                'db_table': 'examperiod_section_exclusion',
                'unique_together': {('exam_period', 'course_section')},
            },
        ),
        migrations.AddField(
            model_name='examperiod',
            name='excluded_sections',
            field=models.ManyToManyField(blank=True, related_name='excluded_in_periods', through='core.ExamPeriodSectionExclusion', to='core.coursesection'),
        ),
    ]
