# Generated by Django 6.0.4 on 2026-05-13 10:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exam_period_section_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimultaneousExamGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('exam_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simultaneous_groups', to='core.examperiod')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simultaneous_groups', to='core.examdateslot')),
            ],
            options={
                'db_table': 'simultaneous_exam_group',
            },
        ),
        migrations.CreateModel(
            name='SimultaneousExamGroupCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simultaneous_group_courses', to='core.coursecatalog')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_courses', to='core.simultaneousexamgroup')),
            ],
            options={
                'db_table': 'simultaneous_exam_group_course',
                'unique_together': {('group', 'course')},
            },
        ),
    ]
